#!/usr/bin/env bash
set -eou pipefail

case "$1" in
    --provider-supported)
        test "$(uname -s)" = "Darwin"
        ;;
    --setup-provider)
        if ! which brew; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
        ;;
    --list-installed-packages)
        brew list --formulae | sort
        ;;
    --provider-id)
        echo homebrew-formulae
        ;;
    --install)
        # BSD xargs doesn't run on empty stdin by default so --no-run-if-empty is not needed
        xargs brew install
        ;;
    *)
        exit 1
        ;;
esac
