#!/usr/bin/env bash
set -euo pipefail

if [ -d ~/dotfiles ]; then
    echo "Dotfiles already installed. Exiting"
    exit 1
fi

TEMP="$(mktemp -d)"
trap 'rm -rf -- "$TEMP"' EXIT

cd "$TEMP"

# Download stowaway
case "$(uname -sm)" in
    "Darwin x86_64")
        release=darwin-amd64
        ;;
    "Darwin arm64")
        release=darwin-arm64
        ;;
    "Linux x86_64")
        release=linux-amd64
        ;;
    *)
        exit 1
        ;;
esac

curl -sLO "https://github.com/jamesbehr/stowaway/releases/latest/download/stowaway-${release}.tar.gz"
curl -sLO "https://github.com/jamesbehr/stowaway/releases/latest/download/stowaway-${release}.tar.gz.sha256sum"
sha256sum --quiet -c "stowaway-${release}.tar.gz.sha256sum"
tar -xzf "stowaway-${release}.tar.gz"

git clone git@github.com:jamesbehr/dotfiles.git ~/dotfiles
cd ~/dotfiles
$TEMP/stowaway stow --target "$HOME" --interactive */
