#!/usr/bin/env bash
set -euo pipefail

DOTFILESRC=${DOTFILESRC:-"$HOME/.dotfilesrc"}

if [ -f "$DOTFILESRC" ]; then
    echo "Loading dotfiles configuration"
    source "$DOTFILESRC"
else
    echo "Creating and loading default dotfiles configuration"
    mv .dotfilesrc "$DOTFILESRC"
    source "$DOTFILESRC"
fi

# Don't attempt to "fold" trees of symlinks by creating a symlink to a
# directory - always create symlinks to the leaves of the tree. This
# prevents "contamination" of the Git repository when an external
# application writes to a directory that was created by Stow. If we
# symlinked to a directory, any files added to that directory would
# suddenly appear in the repository which is undesired behaviour.
IFS=:
for package in $DOTFILES_PACKAGES; do
    echo "Symlinking $package dotfiles"
	stow --restow --no-folding "$package"
done
