#!/usr/bin/env bash
set -euo pipefail

DOTFILES_PACKAGES=git:nvim:zsh:tmux:personal

# Don't attempt to "fold" trees of symlinks by creating a symlink to a
# directory - always create symlinks to the leaves of the tree. This
# prevents "contamination" of the Git repository when an external
# application writes to a directory that was created by Stow. If we
# symlinked to a directory, any files added to that directory would
# suddenly appear in the repository which is undesired behaviour.
IFS=:
for package in $DOTFILES_PACKAGES; do
	stow --restow --no-folding "$package"
done
