return require('packer').startup(function(use)
use("wbthomason/packer.nvim")
use("nvim-lua/plenary.nvim")
use("nvim-lua/popup.nvim")
use("nvim-telescope/telescope.nvim")
use({"nvim-telescope/telescope-fzf-native.nvim", run = "make"})
end)
